### ISSUE TITLE
Replaced names aren't always unique

### ISSUE THREAD

**Issue by CallumHogg** [outragedpinkracoon/harrypotterize_chrome_extension#5]
You can run into a situation where 2 different named entities are assigned same character making for reading the page quite jarring.

**Comment by outragedpinkracoon** [comment]
Do you have an example I could use to test with?

**Comment by bananaCypher** [comment]
Yeah so in this case "Owen Smith" and "Tim Farron" both got replaced by Hermione Granger 

![screenshot from 2016-08-07 20-34-11](https://cloud.githubusercontent.com/assets/11826046/17464757/60afea14-5cde-11e6-974e-d2397c46bdb2.png)

![screenshot from 2016-08-07 20-33-02](https://cloud.githubusercontent.com/assets/11826046/17464759/660a14b2-5cde-11e6-9bd1-b74c4a80ece1.png)
